### ISSUE TITLE
Mac wallet crashing

### ISSUE THREAD

**Issue by mediageni** [ShorelineCrypto/nengcoin#23]
Hi I installed the wallet, but when starting I get this error
System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  dyld: Using shared cache: 52762DF1-0E55-3F8B-9588-8169E6D0EB95
Library not loaded: /usr/local/opt/miniupnpc/lib/libminiupnpc.17.dylib
  Referenced from: /Applications/Nengcoin-Qt.app/Contents/MacOS/Nengcoin-Qt
  Reason: image not found

Binary Images:
       0x10240e000 -        0x102a35fff +org.nengcoin.Nengcoin-Qt ($VERSION - $VERSION) <AE19A7EA-5EFF-3131-BDB3-243239057EAC> /Applications/Nengcoin-Qt.app/Contents/MacOS/Nengcoin-Qt
       0x104d4b000 -        0x104de6fff  dyld (832.7.3) <0D4EA85F-7E30-338B-9215-314A5A5539B6> /usr/lib/dyld

**Comment by ShorelineCrypto** [comment]
Most likely, the macOS version is on unsupported newest versions.  Only Catalina or older versions are supported.

**Comment by ShorelineCrypto** [comment]
The coming new macOS release on rebased v2.0.0 will support big sur.  The pre-release is already out and showing that the new macOS wallet is working in big sur,  possibly working well too on big sur M1 chip because M1 macOS support x86_64 wallet too. 
https://www.reddit.com/r/nengcoin/comments/sbeux5/v20_macos_wallet_working_in_macos_big_sur/
